### ISSUE TITLE
Programs and Services Inner Page Menu - We are taking away the fixed menu functionality. 

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Rapids-Family-Health-2016#16]

**Comment by hemantcci** [comment]
I have removed the fixed functionality. In mobile, inner menu was not fitting so i removed. Problem is there is no link or menu link in inner pages now to navigate between services category. I was thinking of adding program services link in the mobile menu.

**Comment by tgascoigne14** [comment]
That would be awesome if you can add Programs and Services to the mobile
menu. I wasn't sure if this was possible but there needs to be something
for users. Thank you.

_Tina Gascoigne_
_Account Lead_
CCI Studios, Inc.
_Mail:_ 136 Christina St. N., Sarnia, ON N7T 5T9
_Phone:_ (519) 337-8837
_Fax:_ (519) 337-8316
_Email:_ tgascoigne@ccistudios.com
_Web:_ www.ccistudios.com

**2010, 2012 & 2013 Outstanding Business Achievement Award Recipient**

P _Please print this e-mail only if necessary_

_You have received this email because you have a business relationship with
CCI Studios.  If you believe this was done in error or if you would like to
unsubscribe from any future digital communication, please click here
http://www.ccistudios.com/unsubscribe._
