### ISSUE TITLE
Program Sub-Category Landing Page - Sub-category images - Not consistent sizes

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Rapids-Family-Health-2016#5]
Look at the size of the Nutrition images opposed to the Diabetes. When uploading images, they need to automatically be resized to be consistent on every page.

**Comment by hemantcci** [comment]
Actually the minimum height is 450px in cropping for those images if any image having height less than 450px is uploaded it will reduce the width. If we increase the size smaller images it will blur. Should I decrease the minimum height for all images ? Box size will also decrease.

**Comment by tgascoigne14** [comment]
Let's just leave it how it is right now, we are using high quality stock images so there shouldn't be any issues with blurring images. If this changes, I will let you know. Thank you!
